### ISSUE TITLE
快捷键缺失发送快捷键

### ISSUE THREAD

**Issue by xinyuanjiang** [qunarcorp/qtalk#10]
快捷键现在只有截屏和唤起。
严重需要发送alt+s的发送快捷键。

**Comment by fanshisha** [comment]
发送的快捷键有的哦，点击头像——系统设置——热键设置可操作

**Comment by xinyuanjiang** [comment]
并不啊，你说的是老版本吧，我说的是pc新版啊，里面只有截屏和唤起。。。。。。

**Comment by may-liu** [comment]
现在应该有了

**Comment by ChaoCcWang** [comment]
19009080版本 
[系统设置 -> 会话设置 -> 发送消息 ]
可以设置
