### ISSUE TITLE
大文件无法发送

### ISSUE THREAD

**Issue by SuperMAN-ADMINNB** [qunarcorp/qtalk#14]
自行部署完后，大文件发送不出去，小文件没问题，请问如何设置文件大小

**Comment by memacs** [comment]
参考：https://github.com/qunarcorp/ejabberd-open/wiki/%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C
