### ISSUE TITLE
Mac 多显示器无法跨屏截屏

### ISSUE THREAD

**Issue by yulanggong** [qunarcorp/qtalk#17]
发现还没有开源 Mac 的项目，先提这里了。

## 现象
截屏工具只能截取 QTalk 所在显示器的屏幕，无法跨屏截取。

## 软件版本
1.9.952

## 系统版本 
macOS Mojave 10.14.3

**Comment by may-liu** [comment]
收到。暂时。还不支持

**Comment by may-liu** [comment]
新版本将解决这个问题哈，新版本即将发布
