### ISSUE TITLE
以issue的方式总结下最近趟的坑

### ISSUE THREAD

**Issue by JamesLiAndroid** [qunarcorp/qtalk#22]
问题：
1. win客户端卡顿的情况
操作环境为win7，主要有两个地方卡顿：一个是登录后第一次搜索，会卡顿；另一个是清除缓存的时候，直接卡死，只能强制关闭重新登录。

2. win客户端搜索问题
搜索中文名，有一个“打开ID[中文名]的会话”，点击后出现“中文名@domain”的对话框，我按照配置建议，user_id是只有汉语拼音的，并未有中文，导致凭空搜索的用户并不会在库表中存在。我认为这个功能是客户端添加的，应该屏蔽才是。为了验证，我随便搜索了汉字，还是出现了“打开ID[汉字]的会话”，由此断定这是客户端的问题！

由于目前我司并未有QT的开发人员，尚无法修改win客户端，建议官方去除改功能！

部分问题的解决方式：

1. 插入用户无法登录的情况

检查host_user表中frozen_flag是否为0，如果不为0，需要改为0，账号即可登录！

2. 搜索出现混乱的情况，比如搜索出来wangwei@域名这样的结果

需要将configure.ini文件中的domain字段，更改为

`qtalk`

即可

建议搜索的配置文件configure.ini，能更明确的编写下

**Comment by may-liu** [comment]
问题1 应该跟搜索的机器性能有一定关系，目前startalk搜索是依赖后台的；
这个部分我们可以详细的讨论一下

我主要来回答下问题2，这个确实是个feature，这部分功能是给"离职员工"使用的。
比如张三离职了，账号会被回收，但是还在职的同学可能会需要看之前跟张三的聊天记录

那么根据user@domain的原则，当你输入zhangsan 时，会出现“打开ID[zhangsan]的会话”，
即可准确的查看之前跟张三同学的历史记录。

**Comment by JamesLiAndroid** [comment]
@may-liu 

您好，关于您的回复，我做如下反馈：

1. 我目前在搜索不存在的用户的时候，还是会展示这个user@domain选项，点击以后就是个空白的通讯窗口
2. 目前搜索的时候，搜索中文和搜索汉语拼音不太一样。第一，中文搜索已存在于数据库的人员，这样是可以展示到人的，但是点击user@domain这个选项，是不能跳转到正确的人员聊天窗口；第二，汉语拼音已存在于数据库的人员，都能跳转到正确的人员聊天窗口。如果搜索不存在的人员，发现还是会出现这个user@domain选项，点击后发现没有任何意义。

除了以上问题，我们这边还反馈了一个feature性质的问题，就是目前win客户端看不到用户的在线状态。例如，我们点开组织结构，找到某个人员时，在列表中，我们看不到这个用户的在线状态。所以我希望咱这边能添加这个feature。

最后，感谢您和您团队的贡献！

**Comment by ChaoCcWang** [comment]
@JamesLiAndroid 
[user@domain]仅适用于 user id 完全匹配的情况
eg. san.zhang 和 zhangsan.zhang 表示重名为”张三“的两个人, san.zhang@domain 可以打开第一个人的会话, 而zhangsan.zhang@domain 可以打开第二个人的会话
